/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        /** Add Event */
        post: operations["add_event_api_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Options */
        get: operations["event_options_api_event_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendor-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vendor Suggestions */
        get: operations["vendor_suggestions_api_vendor_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Event */
        post: operations["simulate_event_api_events_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event */
        get: operations["event_api_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Items */
        get: operations["items_api_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item */
        get: operations["item_api_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item Comparison */
        get: operations["item_comparison_api_items__item_id__comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History Deal */
        get: operations["history_deal_api_history__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item History */
        get: operations["item_history_api_items__item_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Points */
        put: operations["set_points_api_items__item_id__points_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/confirm-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Points */
        post: operations["confirm_points_api_items__item_id__confirm_points_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/release-bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release Bids */
        post: operations["release_bids_api_items__item_id__release_bids_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_items__item_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vendors */
        get: operations["vendors_api_vendors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors/{vendor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vendor */
        get: operations["vendor_api_vendors__vendor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_api_admin_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item Sessions */
        get: operations["item_sessions_api_items__item_id__sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/negotiations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All Negotiations */
        get: operations["all_negotiations_api_negotiations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Sessions */
        get: operations["event_sessions_api_events__event_id__sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/negotiations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Negotiation */
        post: operations["start_negotiation_api_items__item_id__negotiations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Mode */
        put: operations["set_mode_api_sessions__session_id__mode_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Question */
        post: operations["ask_question_api_sessions__session_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Language */
        put: operations["set_language_api_sessions__session_id__language_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance */
        post: operations["advance_api_sessions__session_id__advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/drafts/{draft_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Draft */
        post: operations["approve_draft_api_sessions__session_id__drafts__draft_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/drafts/{draft_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard Draft */
        post: operations["discard_draft_api_sessions__session_id__drafts__draft_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/accept-offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Offer */
        post: operations["accept_offer_api_sessions__session_id__accept_offer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/hand-back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hand Back */
        post: operations["hand_back_api_sessions__session_id__hand_back_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue Negotiation */
        post: operations["continue_negotiation_api_items__item_id__continue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/accept-deal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Deal */
        post: operations["accept_deal_api_items__item_id__accept_deal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/close-without-deal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Without Deal */
        post: operations["close_without_deal_api_items__item_id__close_without_deal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Event */
        post: operations["approve_event_api_events__event_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Event */
        get: operations["export_event_api_events__event_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveDraftIn */
        ApproveDraftIn: {
            /** Price */
            price?: number | null;
            /** Payment Code */
            payment_code?: string | null;
            /** Text */
            text?: string | null;
        };
        /** CategoryValue */
        CategoryValue: {
            /** Category */
            category: string;
            /** Category Key */
            category_key: string;
            /** Value */
            value: number;
            /** Share */
            share: number;
        };
        /** ComparisonRow */
        ComparisonRow: {
            /** Bid Id */
            bid_id: string;
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /** Vendor Rating */
            vendor_rating: number;
            /** Unit Price */
            unit_price: number;
            /** Effective Price */
            effective_price: number;
            /** Payment Code */
            payment_code: string;
            /** Incoterm */
            incoterm: string;
            /** Delivery Days */
            delivery_days: number;
            /** Validity Days */
            validity_days: number;
            /** Warranty Months */
            warranty_months: number;
            /** Penalty Clause */
            penalty_clause: string;
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "hi" | "mr";
            /** Gap To Target */
            gap_to_target: number;
            /** Is Best Price */
            is_best_price: boolean;
            /** Is Best Effective */
            is_best_effective: boolean;
        };
        /** ComparisonSummary */
        ComparisonSummary: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /** Target */
            target: number;
            /** Limit */
            limit: number;
            /** Best Price */
            best_price: number | null;
            /** Best Effective Price */
            best_effective_price: number | null;
            /** Best Effective Bid Id */
            best_effective_bid_id: string | null;
            /** Spread */
            spread: number | null;
            /** Opportunity */
            opportunity: boolean;
            /** Potential Delta */
            potential_delta: number;
        };
        /** ComparisonView */
        ComparisonView: {
            /** Item Id */
            item_id: string;
            /** Rows */
            rows: components["schemas"]["ComparisonRow"][];
            summary: components["schemas"]["ComparisonSummary"];
        };
        /** Dashboard */
        Dashboard: {
            kpis: components["schemas"]["Kpis"];
            /** Events */
            events: components["schemas"]["EventView"][];
            /** Value By Category */
            value_by_category: components["schemas"]["CategoryValue"][];
            /** Top Vendors */
            top_vendors: components["schemas"]["VendorValue"][];
            /** Opportunities */
            opportunities: components["schemas"]["Opportunity"][];
            /** Status Distribution */
            status_distribution: {
                [key: string]: number;
            };
            /** Item State Distribution */
            item_state_distribution: {
                [key: string]: number;
            };
            delta_generated: components["schemas"]["DeltaGenerated"];
            insight: components["schemas"]["Insight"] | null;
        };
        /** DeltaGenerated */
        DeltaGenerated: {
            /** Savings */
            savings: number;
            /** Uplift */
            uplift: number;
            /** Total */
            total: number;
        };
        /** DraftView */
        DraftView: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "offer" | "accept" | "handback";
            /** Price */
            price: number | null;
            /** Payment Code */
            payment_code: string | null;
            /** Text */
            text: string;
            /** Rationale */
            rationale: string;
            /** Tactic */
            tactic?: string | null;
            /**
             * Created
             * Format: date-time
             */
            created: string;
        };
        /** EligibilityView */
        EligibilityView: {
            /** Eligible */
            eligible: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** EventDetail */
        EventDetail: {
            event: components["schemas"]["EventView"];
            /** Items */
            items: components["schemas"]["ItemView"][];
        };
        /** EventView */
        EventView: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "shopping_cart" | "scrap_sale";
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Plant */
            plant: string;
            /** Purch Org */
            purch_org: string;
            /** Purch Group */
            purch_group: string;
            /** Category */
            category: string;
            /** Category Key */
            category_key: string;
            /** Requestor */
            requestor: string;
            /** Cost Centre */
            cost_centre: string;
            /**
             * Created
             * Format: date
             */
            created: string;
            /**
             * Approval Date
             * Format: date
             */
            approval_date: string;
            /**
             * Due
             * Format: date
             */
            due: string;
            /** Source Cart No */
            source_cart_no: string | null;
            /** Hero */
            hero: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "received" | "in_progress" | "closed";
            eligibility: components["schemas"]["EligibilityView"];
            /** Item Count */
            item_count: number;
            /** Vendor Count */
            vendor_count: number;
            /** Reference Value */
            reference_value: number;
            /** Quoted Value */
            quoted_value: number;
            /** Potential Delta */
            potential_delta: number;
            /** Realised Delta */
            realised_delta: number;
            /** Final Value */
            final_value: number | null;
            /** Original Value */
            original_value: number | null;
            /** Items Negotiated */
            items_negotiated: number;
            /** Vendors Participated */
            vendors_participated: number;
            /** Duration Minutes */
            duration_minutes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandBackIn */
        HandBackIn: {
            /** Reason */
            reason?: string | null;
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
        };
        /** HistoryDeal */
        HistoryDeal: {
            deal: components["schemas"]["HistoryPoint"];
            /** Similar */
            similar: components["schemas"]["HistoryPoint"][];
            /** Average Similar */
            average_similar: number | null;
            /** Vendor Rating */
            vendor_rating: number;
            /** Explanation */
            explanation: string;
        };
        /** HistoryPoint */
        HistoryPoint: {
            /** Id */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Description */
            description: string;
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /** Category Key */
            category_key: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "EA" | "AU" | "KG" | "TON" | "LOT";
            /** Unit Price */
            unit_price: number;
            /** Qty */
            qty: number;
            /** Value */
            value: number;
            /** Negotiated */
            negotiated: boolean;
            /** Original Price */
            original_price: number | null;
            /** Benchmark */
            benchmark: number | null;
            /** Basis */
            basis: string;
            /** Result */
            result: number | null;
            /** Result Pct */
            result_pct: number | null;
            /** Decision */
            decision: ("gain" | "even" | "loss") | null;
        };
        /** HistoryRow */
        HistoryRow: {
            /** Id */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Description */
            description: string;
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /** Category Key */
            category_key: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "EA" | "AU" | "KG" | "TON" | "LOT";
            /** Unit Price */
            unit_price: number;
            /** Qty */
            qty: number;
            /** Value */
            value: number;
            /** Negotiated */
            negotiated: boolean;
            /** Original Price */
            original_price: number | null;
            /** Benchmark */
            benchmark: number | null;
            /** Basis */
            basis: string;
            /** Result */
            result: number | null;
            /** Result Pct */
            result_pct: number | null;
            /** Decision */
            decision: ("gain" | "even" | "loss") | null;
            /** Value Delta */
            value_delta: number | null;
        };
        /** HistoryStats */
        HistoryStats: {
            /** Count */
            count: number;
            /** Average */
            average: number;
            /** Minimum */
            minimum: number;
            /** Maximum */
            maximum: number;
            /** Last Price */
            last_price: number;
            /**
             * Last Date
             * Format: date
             */
            last_date: string;
        };
        /** HistorySummary */
        HistorySummary: {
            /** Deals */
            deals: number;
            /** Negotiated Deals */
            negotiated_deals: number;
            /** Gains */
            gains: number;
            /** Evens */
            evens: number;
            /** Losses */
            losses: number;
            /** Net Result */
            net_result: number;
        };
        /** HistoryView */
        HistoryView: {
            /** Item Id */
            item_id: string;
            /**
             * Basis
             * @enum {string}
             */
            basis: "description" | "category" | "none";
            /** Records */
            records: components["schemas"]["HistoryPoint"][];
            stats: components["schemas"]["HistoryStats"] | null;
            last_negotiated: components["schemas"]["HistoryPoint"] | null;
        };
        /** Insight */
        Insight: {
            /** Event Id */
            event_id: string;
            /** Item Id */
            item_id: string;
            /** Description */
            description: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /** Spread */
            spread: number;
            /** Best Price */
            best_price: number;
            /** Worst Price */
            worst_price: number;
        };
        /** InsightView */
        InsightView: {
            /** Kind */
            kind: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "info" | "good" | "warn";
            /** Text */
            text: string;
        };
        /** Intelligence */
        Intelligence: {
            /** Current Bid */
            current_bid: number;
            /** Target */
            target: number;
            /** Limit */
            limit: number;
            /** Latest Vendor Offer */
            latest_vendor_offer: number;
            /** Our Offer */
            our_offer: number | null;
            /** Movement */
            movement: number;
            /** Potential Delta */
            potential_delta: number;
            /** Delta If Accepted */
            delta_if_accepted: number | null;
            /** Within Limit */
            within_limit: boolean;
            /** Recommendation */
            recommendation: string;
        };
        /** Invitee */
        Invitee: {
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /** Rating */
            rating: number;
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "hi" | "mr";
            /** Responded */
            responded: boolean;
            toughness: components["schemas"]["Toughness"];
        };
        /** ItemDetail */
        ItemDetail: {
            item: components["schemas"]["ItemView"];
            event: components["schemas"]["EventView"];
            /** Invitees */
            invitees: components["schemas"]["Invitee"][];
            comparison: components["schemas"]["ComparisonView"];
            outcome: components["schemas"]["OutcomeView"] | null;
            value_eligibility: components["schemas"]["EligibilityView"];
            bids_eligibility: components["schemas"]["EligibilityView"];
            /** Active Session Id */
            active_session_id?: string | null;
            /** Latest Session Status */
            latest_session_status?: string | null;
        };
        /**
         * ItemRow
         * @description An item with just enough event context for cross-event lists.
         */
        ItemRow: {
            /** Id */
            id: string;
            /** Event Id */
            event_id: string;
            /** Position */
            position: number;
            /** Description */
            description: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "service" | "goods" | "scrap";
            /** Qty */
            qty: number;
            /**
             * Unit
             * @enum {string}
             */
            unit: "EA" | "AU" | "KG" | "TON" | "LOT";
            /** Reference Price */
            reference_price: number;
            /** Target */
            target: number;
            /** Limit */
            limit: number;
            /** Points Set */
            points_set: boolean;
            /** Objective */
            objective: ("reduce_price" | "improve_lead_time" | "improve_payment_terms" | "improve_commercial_terms") | null;
            /** Incoterm */
            incoterm: string;
            /** Delivery Days */
            delivery_days: number;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "points_reviewed" | "awaiting_bids" | "bids_in" | "analyzed" | "negotiating" | "result_pending" | "awaiting_approval" | "closed" | "handed_back";
            /** Bid Count */
            bid_count: number;
            /** Min Bids Met */
            min_bids_met: boolean;
            /** Best Bid */
            best_bid: number | null;
            /** Best Bid Vendor Id */
            best_bid_vendor_id: string | null;
            /** Best Bid Vendor */
            best_bid_vendor: string | null;
            /** Best Effective Price */
            best_effective_price: number | null;
            /** Gap */
            gap: number | null;
            /** Potential Delta */
            potential_delta: number | null;
            /** Within Limit */
            within_limit: boolean | null;
            /** Value */
            value: number;
            /**
             * Recommendation
             * @enum {string}
             */
            recommendation: "waiting" | "negotiate" | "accept" | "review" | "done";
            /** Event Title */
            event_title: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /** Category */
            category: string;
            /** Category Key */
            category_key: string;
            /**
             * Event Status
             * @enum {string}
             */
            event_status: "received" | "in_progress" | "closed";
        };
        /** ItemView */
        ItemView: {
            /** Id */
            id: string;
            /** Event Id */
            event_id: string;
            /** Position */
            position: number;
            /** Description */
            description: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "service" | "goods" | "scrap";
            /** Qty */
            qty: number;
            /**
             * Unit
             * @enum {string}
             */
            unit: "EA" | "AU" | "KG" | "TON" | "LOT";
            /** Reference Price */
            reference_price: number;
            /** Target */
            target: number;
            /** Limit */
            limit: number;
            /** Points Set */
            points_set: boolean;
            /** Objective */
            objective: ("reduce_price" | "improve_lead_time" | "improve_payment_terms" | "improve_commercial_terms") | null;
            /** Incoterm */
            incoterm: string;
            /** Delivery Days */
            delivery_days: number;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "points_reviewed" | "awaiting_bids" | "bids_in" | "analyzed" | "negotiating" | "result_pending" | "awaiting_approval" | "closed" | "handed_back";
            /** Bid Count */
            bid_count: number;
            /** Min Bids Met */
            min_bids_met: boolean;
            /** Best Bid */
            best_bid: number | null;
            /** Best Bid Vendor Id */
            best_bid_vendor_id: string | null;
            /** Best Bid Vendor */
            best_bid_vendor: string | null;
            /** Best Effective Price */
            best_effective_price: number | null;
            /** Gap */
            gap: number | null;
            /** Potential Delta */
            potential_delta: number | null;
            /** Within Limit */
            within_limit: boolean | null;
            /** Value */
            value: number;
            /**
             * Recommendation
             * @enum {string}
             */
            recommendation: "waiting" | "negotiate" | "accept" | "review" | "done";
        };
        /** Kpis */
        Kpis: {
            /** Total Events */
            total_events: number;
            /** Open Events */
            open_events: number;
            /** Items */
            items: number;
            /** Vendors */
            vendors: number;
            /** Total Value */
            total_value: number;
            /** Potential Savings */
            potential_savings: number;
            /** Potential Uplift */
            potential_uplift: number;
            /** Potential Total */
            potential_total: number;
            /** Negotiations In Progress */
            negotiations_in_progress: number;
            /** Completed Negotiations */
            completed_negotiations: number;
            /** Realised Savings */
            realised_savings: number;
            /** Realised Uplift */
            realised_uplift: number;
            /** Realised Total */
            realised_total: number;
        };
        /** LanguageIn */
        LanguageIn: {
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "hi" | "mr";
        };
        /** MessageIn */
        MessageIn: {
            /** Price */
            price: number;
            /** Payment Code */
            payment_code?: string | null;
            /** Text */
            text?: string | null;
        };
        /** ModeIn */
        ModeIn: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "approve" | "manual";
        };
        /** NewEvent */
        NewEvent: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /** Title */
            title?: string | null;
            /** Category Key */
            category_key: string;
            /** Category Label */
            category_label?: string | null;
            /** Company Id */
            company_id: string;
            /** Company */
            company: string;
            /** Plant */
            plant: string;
            /** Purch Org */
            purch_org: string;
            /** Purch Group */
            purch_group: string;
            /** Requestor */
            requestor: string;
            /** Cost Centre */
            cost_centre: string;
            /**
             * Due
             * Format: date
             */
            due: string;
            /** Source Cart No */
            source_cart_no?: string | null;
            /** Vendor Ids */
            vendor_ids: string[];
            /** Items */
            items: components["schemas"]["NewItem"][];
        };
        /** NewItem */
        NewItem: {
            /** Description */
            description: string;
            /** Qty */
            qty: number;
            /**
             * Unit
             * @enum {string}
             */
            unit: "EA" | "AU" | "KG" | "TON" | "LOT";
            /** Reference Price */
            reference_price: number;
            /** Incoterm */
            incoterm?: string | null;
            /** Delivery Days */
            delivery_days?: number | null;
        };
        /** Opportunity */
        Opportunity: {
            /** Event Id */
            event_id: string;
            /** Item Id */
            item_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "points_reviewed" | "awaiting_bids" | "bids_in" | "analyzed" | "negotiating" | "result_pending" | "awaiting_approval" | "closed" | "handed_back";
            /** Best Bid */
            best_bid: number;
            /** Target */
            target: number;
            /** Gap */
            gap: number;
            /** Potential Delta */
            potential_delta: number;
        };
        /** OutcomeView */
        OutcomeView: {
            /** Item Id */
            item_id: string;
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /** Qty */
            qty: number;
            /** Original Price */
            original_price: number;
            /** Final Price */
            final_price: number;
            /** Value Delta */
            value_delta: number;
            /** Negotiated */
            negotiated: boolean;
            /** Payment Code */
            payment_code: string;
            /** Incoterm */
            incoterm: string;
            /**
             * Closed Date
             * Format: date
             */
            closed_date: string;
            /** Duration Minutes */
            duration_minutes: number;
        };
        /** PointsIn */
        PointsIn: {
            /** Target */
            target: number;
            /** Limit */
            limit: number;
            /** Objective */
            objective?: ("reduce_price" | "improve_lead_time" | "improve_payment_terms" | "improve_commercial_terms") | null;
        };
        /** QuestionIn */
        QuestionIn: {
            /** Text */
            text: string;
        };
        /** ReleaseIn */
        ReleaseIn: {
            /** Vendor Ids */
            vendor_ids?: string[] | null;
        };
        /** ResetResult */
        ResetResult: {
            /** Events */
            events: number;
        };
        /** SessionActions */
        SessionActions: {
            /** Can Advance */
            can_advance: boolean;
            /** Can Send */
            can_send: boolean;
            /** Can Accept Offer */
            can_accept_offer: boolean;
            /** Can Hand Back */
            can_hand_back: boolean;
            /** Can Continue */
            can_continue: boolean;
            /** Can Accept Deal */
            can_accept_deal: boolean;
        };
        /**
         * SessionRow
         * @description One negotiation in the all-negotiations list: the summary plus where it belongs.
         */
        SessionRow: {
            /** Id */
            id: string;
            /** Item Id */
            item_id: string;
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "approve" | "manual";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "agreed" | "handed_back";
            /** Round */
            round: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Agreed Price */
            agreed_price: number | null;
            /** Event Id */
            event_id: string;
            /** Event Title */
            event_title: string;
            /** Item Description */
            item_description: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /** Qty */
            qty: number;
            /** Unit */
            unit: string;
            /** Original Price */
            original_price: number;
            /** Vendor Offer */
            vendor_offer: number;
            /** Ended At */
            ended_at: string | null;
        };
        /** SessionSummary */
        SessionSummary: {
            /** Id */
            id: string;
            /** Item Id */
            item_id: string;
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "approve" | "manual";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "agreed" | "handed_back";
            /** Round */
            round: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Agreed Price */
            agreed_price: number | null;
        };
        /** SessionView */
        SessionView: {
            /** Id */
            id: string;
            /** Item Id */
            item_id: string;
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "approve" | "manual";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "agreed" | "handed_back";
            /** Round */
            round: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Agreed Price */
            agreed_price: number | null;
            /** Event Id */
            event_id: string;
            actions: components["schemas"]["SessionActions"];
            /** Item Description */
            item_description: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "hi" | "mr";
            /**
             * Unit
             * @enum {string}
             */
            unit: "EA" | "AU" | "KG" | "TON" | "LOT";
            /** Qty */
            qty: number;
            /** Original Price */
            original_price: number;
            /** Our Offer */
            our_offer: number | null;
            /** Vendor Offer */
            vendor_offer: number;
            /** Vendor Payment */
            vendor_payment: string;
            /** Vendor Final */
            vendor_final: boolean;
            /** Agreed Payment */
            agreed_payment: string | null;
            /** Agreed Delta */
            agreed_delta: number | null;
            /** Original Value */
            original_value: number;
            /** Agreed Value */
            agreed_value: number | null;
            /** Handback Reason */
            handback_reason: string | null;
            /** Vendor Ended */
            vendor_ended: boolean;
            /** Ended At */
            ended_at: string | null;
            /** Turns */
            turns: components["schemas"]["TurnView"][];
            pending_draft: components["schemas"]["DraftView"] | null;
            intelligence: components["schemas"]["Intelligence"];
            strategy: components["schemas"]["Strategy"];
        };
        /** SimulateIn */
        SimulateIn: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
        };
        /** StartIn */
        StartIn: {
            /** Vendor Id */
            vendor_id?: string | null;
            /**
             * Mode
             * @default approve
             * @enum {string}
             */
            mode: "auto" | "approve" | "manual";
        };
        /**
         * Strategy
         * @description Where the conversation stands, from what the vendor has actually done (never its hidden settings).
         */
        Strategy: {
            /** Round */
            round: number;
            /** Max Rounds */
            max_rounds: number;
            /**
             * Phase
             * @enum {string}
             */
            phase: "opening" | "probing" | "trading" | "pressing" | "closing" | "done";
            /**
             * Stance
             * @enum {string}
             */
            stance: "unknown" | "open" | "firm" | "open_on_terms" | "crawling";
            /** Stance Note */
            stance_note: string;
            /** Mood */
            mood: number;
            /**
             * Mood Label
             * @enum {string}
             */
            mood_label: "calm" | "impatient" | "frustrated" | "walking_away";
            /** Tactics Used */
            tactics_used: string[];
            /** Elapsed Minutes */
            elapsed_minutes: number;
            /** Alternative */
            alternative: string | null;
            history: components["schemas"]["Toughness"];
        };
        /**
         * Toughness
         * @description How hard a vendor has been to move, judged from its past negotiated deals.
         */
        Toughness: {
            /**
             * Level
             * @enum {string}
             */
            level: "unknown" | "flexible" | "firm" | "hard";
            /** Negotiated Deals */
            negotiated_deals: number;
            /** Average Concession Pct */
            average_concession_pct: number | null;
            /** Note */
            note: string;
        };
        /** TurnView */
        TurnView: {
            /** Seq */
            seq: number;
            /**
             * Speaker
             * @enum {string}
             */
            speaker: "us" | "vendor";
            /**
             * Author
             * @enum {string}
             */
            author: "bot" | "human" | "vendor";
            /** Text */
            text: string;
            /** Price */
            price: number | null;
            /** Payment Code */
            payment_code: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Tactic */
            tactic?: string | null;
            /**
             * Delay Minutes
             * @default 0
             */
            delay_minutes: number;
            /**
             * Elapsed Minutes
             * @default 0
             */
            elapsed_minutes: number;
            /**
             * Insights
             * @default []
             */
            insights: components["schemas"]["InsightView"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VendorBidRow */
        VendorBidRow: {
            /** Item Id */
            item_id: string;
            /** Event Id */
            event_id: string;
            /** Description */
            description: string;
            /** Unit Price */
            unit_price: number;
            /** Qty */
            qty: number;
        };
        /** VendorDetail */
        VendorDetail: {
            vendor: components["schemas"]["VendorView"];
            /** History */
            history: components["schemas"]["HistoryPoint"][];
            history_summary: components["schemas"]["HistorySummary"];
            /** Recent Bids */
            recent_bids: components["schemas"]["VendorBidRow"][];
        };
        /** VendorValue */
        VendorValue: {
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /** Value */
            value: number;
            /** Share */
            share: number;
        };
        /** VendorView */
        VendorView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Sap No */
            sap_no: string;
            /**
             * Type
             * @enum {string}
             */
            type: "supplier" | "scrap_buyer";
            /** Categories */
            categories: string[];
            /** Rating */
            rating: number;
            /** Payment Pref */
            payment_pref: string;
            /** Past Deals */
            past_deals: number;
            /** Live Bid Count */
            live_bid_count: number;
            /** Quoted Value */
            quoted_value: number;
            /** Closed Deals */
            closed_deals: number;
            /** History Deals */
            history_deals: number;
            toughness: components["schemas"]["Toughness"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                q?: string | null;
                direction?: ("buy" | "sell") | null;
                status?: ("received" | "in_progress" | "closed") | null;
                category_key?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_event_api_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_options_api_event_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    vendor_suggestions_api_vendor_suggestions_get: {
        parameters: {
            query: {
                direction: "buy" | "sell";
                category_key: string;
                q?: string[];
                category_label?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_event_api_events_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_api_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    items_api_items_get: {
        parameters: {
            query?: {
                event_id?: string | null;
                has_bids?: boolean | null;
                recommendation?: ("waiting" | "negotiate" | "accept" | "review" | "done") | null;
                direction?: ("buy" | "sell") | null;
                q?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query?: {
                direction?: ("buy" | "sell") | null;
                category_key?: string | null;
                q?: string | null;
                negotiated?: boolean | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_api_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_comparison_api_items__item_id__comparison_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_deal_api_history__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDeal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_history_api_items__item_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_points_api_items__item_id__points_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_points_api_items__item_id__confirm_points_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_bids_api_items__item_id__release_bids_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReleaseIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_items__item_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vendors_api_vendors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorView"][];
                };
            };
        };
    };
    vendor_api_vendors__vendor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_admin_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetResult"];
                };
            };
        };
    };
    item_sessions_api_items__item_id__sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    all_negotiations_api_negotiations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRow"][];
                };
            };
        };
    };
    event_sessions_api_events__event_id__sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_negotiation_api_items__item_id__negotiations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_mode_api_sessions__session_id__mode_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_question_api_sessions__session_id__questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_language_api_sessions__session_id__language_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LanguageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_api_sessions__session_id__advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_draft_api_sessions__session_id__drafts__draft_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveDraftIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_draft_api_sessions__session_id__drafts__draft_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_offer_api_sessions__session_id__accept_offer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hand_back_api_sessions__session_id__hand_back_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["HandBackIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_negotiation_api_items__item_id__continue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_deal_api_items__item_id__accept_deal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_without_deal_api_items__item_id__close_without_deal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_event_api_events__event_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_event_api_events__event_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
